sbox now allow specify 'dirty' dir
refactor

add work dir option

add option dirty_dir
refactor2

diff --git a/sbox b/sbox
--- a/sbox
+++ b/sbox
@@ -15,13 +15,18 @@
 #
 # Usage: sbox [OPTION] PROGRAM
 #
+
+# TODO: Only declare variables, move define operation after processing command line variables.
 CONTAINER_NAME=default					# default container name
 SNAPSHOT_DIR="snapshot"					# default snapshot directory name
+ROOTFS_DIR='/'							# default rootfs(lower level) path
+DIRTY_DIR="dirty"						# default dirty directory name
+WORK_DIR="work"							# default work directory name
 
 MAP_USER_ROOT=""
 NO_NEW_PRIVS=false
 USER="root"
-PREFIX_DIR="/sbox"
+MGT_DIR="/tmp/sbox"						# where to storage sbox management files
 
 # default seccomp profile
 # deny these syscalls once in sandbox
@@ -96,6 +101,11 @@ CAP_SYSLOG,\
 CAP_WAKE_ALARM\
 "
 
+usage() {
+	echo "usage: $0: [OPTION] PROGRAM"
+	echo "Run with '--help' for more information."
+}
+
 help() {
 	echo "usage: $0: [OPTION] PROGRAM"
 	echo "Run <PROGRAM> in a sandbox environment without writting to rootfs."
@@ -112,8 +122,15 @@ help() {
 	echo "	-d, --snapshot-dir DIR"
 	echo "		Directory to store files generated by sandboxed program."
 	echo "		Default location is /tmp/sbox/<NAME>/snapshot."
-	echo "		You can specify the <DIR> to disk if you want to save "
-	echo "		generated files."
+	echo ""
+	echo "	-t, --dirty-dir DIR"
+	echo "		Directory to cache temporary changes to filesystem."
+	echo "		Default location is /tmp/sbox/<NAME>/dirty."
+	echo ""
+	echo "	-w, --work-dir DIR"
+	echo "		Directory to store overlayfs's internal files."
+	echo "		Must be under the same mount of dirty_dir"
+	echo "		Default location is /tmp/sbox/<NAME>/work."
 	echo ""
 	echo "	-B, --seccomp-blacklist SYSCALLS"
 	echo "		Deny syscalls that are in list SYSCALLS inside sandbox."
@@ -152,8 +169,8 @@ help() {
 #############################################################
 mount_teardown() {
 	# umount overlayfs
-	if mountpoint -q "/tmp$PREFIX_DIR/$CONTAINER_NAME/rootfs"; then
-		umount "/tmp$PREFIX_DIR/$CONTAINER_NAME/rootfs"
+	if mountpoint -q "$MGT_DIR/$CONTAINER_NAME/rootfs"; then
+		umount "$MGT_DIR/$CONTAINER_NAME/rootfs"
 	fi
 
 	rm "$PIPE1" >/dev/null 2>&1
@@ -171,6 +188,8 @@ for arg in "$@"; do
 		"--container-name")       set -- "$@" "-n" ;;
 		"--user-root")            set -- "$@" "-u" ;;
 		"--snapshot-dir")         set -- "$@" "-d" ;;
+		"--dirty-dir")            set -- "$@" "-t" ;;
+		"--work-dir")             set -- "$@" "-w" ;;
 		"--auto-commit")          set -- "$@" "-c" ;;
 		"--cgroup")               set -- "$@" "-g" ;;
 		"--no-new-privs")         set -- "$@" "-N" ;;
@@ -218,12 +237,14 @@ AA_PROFILE=
 AA_PROFILE_NAMES=
 CGROUPS=
 
-while getopts n:u:d:c:g:NB:D:A:vh opt; do
+while getopts n:u:d:t:w:c:g:NB:D:A:vh opt; do
 	case $opt in
 		n)                  CONTAINER_NAME=$OPTARG ;;
 		u)                  MAP_USER_ROOT="--map-root-user"
 		                    USER=$OPTARG ;;
 		d)                  SNAPSHOT_DIR=$OPTARG ;;
+		t)                  DIRTY_DIR=$OPTARG ;;
+		w)                  WORK_DIR=$OPTARG ;;
 		c)                  AUTO_COMMIT="$(true_or_false $OPTARG)" # env var
 		                    if [ -z "$AUTO_COMMIT" ]; then
 		                        echo "Unrecognized Value: $OPTARG" >&2
@@ -240,7 +261,7 @@ while getopts n:u:d:c:g:NB:D:A:vh opt; do
 		                    VERBOSE=true ;;
 		h)                  help
 		                    exit ;;
-		?)                  help
+		?)                  usage
 		                    exit 2 ;;
 	esac
 done
@@ -255,9 +276,12 @@ fi
 # check positional arguments
 if [ -z "$1" ]; then
 	echo "nothing to run!" >&2
-	help
+	usage
 	exit 2
 fi
+
+# TODO: Read config under $CONTAINER_NAME, assign unset variables with values in config.
+#       If container not created, assign unset variables to default.
 
 # check if cgroup is not enabled
 if [ ! -z "$CGROUPS" ] && [ -z "$(grep '\<cgroup\>' /proc/filesystems)" ]; then
@@ -337,18 +361,26 @@ debootstrap_firmware_layer() {
 debootstrap_sandbox() {
 	local name="$CONTAINER_NAME"
 
-	mkdir "/tmp$PREFIX_DIR" >/dev/null 2>&1
-	pushd "/tmp$PREFIX_DIR" >/dev/null
+	mkdir "$MGT_DIR" >/dev/null 2>&1
+	pushd "$MGT_DIR" >/dev/null
 
 	mkdir -p "$name" >/dev/null 2>&1
 	pushd "$name" >/dev/null
-	SNAPSHOT_DIR=$(realpath -m "$SNAPSHOT_DIR") # to abs path
+	SNAPSHOT_DIR=$(realpath -m "$SNAPSHOT_DIR") # resolve to abs path
+	DIRTY_DIR=$(realpath -m "$DIRTY_DIR") # resolve to abs path
+	WORK_DIR=$(realpath -m "$WORK_DIR") # resolve to abs path
 	popd >/dev/null
-	[ ! -d "$name" ] && echo "Create new container \"$CONTAINER_NAME\" with snapshot at $SNAPSHOT_DIR"
 
 	# create/load rootfs
-	mkdir -p "$name/dirty" >/dev/null 2>&1
-	mkdir -p "$name/workdir" >/dev/null 2>&1
+	mkdir -p "$DIRTY_DIR" >/dev/null 2>&1
+	mkdir -p "$WORK_DIR" >/dev/null 2>&1
+	local m1=$(df -P "$DIRTY_DIR" | tail -1 | cut -d' ' -f 1)
+	local m2=$(df -P "$WORK_DIR" | tail -1 | cut -d' ' -f 1)
+	if [ "$m1" != "$m2" ]; then
+		echo "Dirty directory and Work directory must reside under the same mount." >&2
+		exit 1
+	fi
+
 	mkdir -p "$name/rootfs" >/dev/null 2>&1
 	firmware_dir=$(realpath "$name/firmware") # to abs path
 	debootstrap_firmware_layer "$firmware_dir" >/dev/null 2>&1
@@ -363,8 +395,12 @@ debootstrap_sandbox() {
 	# LOW <----------------------------------> HIGH
 	# [/] -> [firmware] -> [snapshot_dir] -> [dirty] <= file i/o
 	mount -t overlay \
-		-o lowerdir="$SNAPSHOT_DIR":"$firmware_dir":/,upperdir="dirty",workdir="workdir" \
+		-o lowerdir="$SNAPSHOT_DIR":"$firmware_dir":/,upperdir="$DIRTY_DIR",workdir="$WORK_DIR" \
 		overlay "rootfs"
+	if [ $? -ne 0 ]; then
+		echo "Unable to mount overlayfs!" >&2
+		exit 1
+	fi
 
 	popd >/dev/null
 }
@@ -716,8 +752,8 @@ eth_setup() {
 		fail "Unable to get unshare pid when setting up network!"
 	fi
 	$VERBOSE && echo "sandbox pid: $pid"
-	echo $pid > "/tmp$PREFIX_DIR/$CONTAINER_NAME/container.pid" # write pid file
-	echo "SBOX_PID=\"$pid\"" >> "/tmp$PREFIX_DIR/$CONTAINER_NAME/config"
+	echo $pid > "$MGT_DIR/$CONTAINER_NAME/container.pid" # write pid file
+	echo "SBOX_PID=\"$pid\"" >> "$MGT_DIR/$CONTAINER_NAME/config"
 
 	# apply cgroup to sandbox
 	[ ! -z "$CGROUPS" ] && cgroup_apply "$pid" "$CGROUPS"
@@ -774,7 +810,7 @@ eth_teardown() {
 #############################################################
 get_container_pid() {
 	local name="$1"
-	local pid=$(cat "/tmp$PREFIX_DIR/$name/container.pid" 2>/dev/null)
+	local pid=$(cat "$MGT_DIR/$name/container.pid" 2>/dev/null)
 	if [ ! -z "$pid" ] && (ps -p "$pid" >/dev/null 2>&1); then
 		echo "$pid"
 		return 0
@@ -828,10 +864,13 @@ save_config() {
 	shift
 	{
 		echo "SBOX_NAME=\"$CONTAINER_NAME\""
+		echo "SBOX_LOC=\"$MGT_DIR/$CONTAINER_NAME\""
 		echo "SBOX_SNAPSHOT_DIR=\"$SNAPSHOT_DIR\""
+		echo "SBOX_DIRTY_DIR=\"$DIRTY_DIR\""
+		echo "SBOX_WORK_DIR=\"$WORK_DIR\""
+		echo "SBOX_ROOTFS_DIR='$ROOTFS_DIR'"
 		echo "SBOX_CAP_DROPS=\"$CAP_DROPS\""
 		echo "SBOX_SYSCALL_DENYS=\"${SYSCALL_DENYS[@]}\""
-		echo "SBOX_PREFIX_DIR=\"$PREFIX_DIR\""
 		echo "SBOX_CGROUPS=\"$CGROUPS\""
 		echo "SBOX_AA_PROFILE=\"$AA_PROFILE\""
 		echo "SBOX_AA_PROFILE_NAMES=\"$AA_PROFILE_NAMES\""
@@ -872,7 +911,7 @@ eth_init
 eth_setup $PIPE1 $PIPE2 & # async
 
 # save current sandbox's settings
-save_config "/tmp$PREFIX_DIR/$CONTAINER_NAME/config" $@
+save_config "$MGT_DIR/$CONTAINER_NAME/config" $@
 
 # syscall name to kernel reference number
 SYSCALL_DENYS=($(syscall2nums "${SYSCALL_DENYS[@]}"))
@@ -897,7 +936,7 @@ unshare --kill-child --fork \
 		rm $PIPE2
 
 		# mountings
-		cd "/tmp$PREFIX_DIR/$CONTAINER_NAME"
+		cd "$MGT_DIR/$CONTAINER_NAME"
 		mount -t proc proc rootfs/proc
 		mount -t tmpfs tmpfs rootfs/tmp
 		mount -t sysfs -r sysfs rootfs/sys
@@ -949,10 +988,10 @@ $KILLED && stty sane # to fix shell's strange behavior when child process was ki
 # $KILLED && kill -9 $$
 
 #Save snapshot
-pushd "/tmp$PREFIX_DIR/$CONTAINER_NAME" >/dev/null
+pushd "$MGT_DIR/$CONTAINER_NAME" >/dev/null
 
-tree -Ca "dirty"
-size=$(du -sPh "dirty" | cut -f1-1)
+tree -Ca "$DIRTY_DIR"
+size=$(du -sPh "$DIRTY_DIR" | cut -f1-1)
 verbose_cmd=$($VERBOSE && echo '--verbose')
 echo "$size data generated."
 
@@ -963,14 +1002,15 @@ if [ -z "$AUTO_COMMIT" ]; then
 		case $yn in
 			"" | [Yy]* )
 				sbox-fstool commit "$CONTAINER_NAME" "$verbose_cmd" \
+					--dirty-dir "$DIRTY_DIR" \
 					--snapshot-dir "$SNAPSHOT_DIR" && \
-				echo "committed to $(realpath $SNAPSHOT_DIR)"
+				echo "committed to $SNAPSHOT_DIR"
 				break
 				;;
 			[Nn]* )
 				echo "Abort."
-				$VERBOSE && echo "remove $(realpath -m dirty)"
-				rm -r "dirty" >/dev/null 2>&1
+				$VERBOSE && echo "remove $DIRTY_DIR"
+				rm -r "$DIRTY_DIR" >/dev/null 2>&1
 				exit 0
 				;;
 			* ) ;;
@@ -979,13 +1019,14 @@ if [ -z "$AUTO_COMMIT" ]; then
 elif $AUTO_COMMIT; then
 	echo "auto commit"
 	sbox-fstool commit "$CONTAINER_NAME" "$verbose_cmd" \
+		--dirty-dir "$DIRTY_DIR" \
 		--snapshot-dir "$SNAPSHOT_DIR" && \
-	echo "committed to $(realpath $SNAPSHOT_DIR)"
+	echo "committed to $SNAPSHOT_DIR"
 	[ -z "$AUTO_MERGE" ] && exit 0 # when -c flag set via sbox not sbox-mgt
 else
 	echo "discard changes"
-	$VERBOSE && echo "remove $(realpath -m dirty)"
-	rm -r "dirty" >/dev/null 2>&1
+	$VERBOSE && echo "remove $DIRTY_DIR"
+	rm -r "$DIRTY_DIR" >/dev/null 2>&1
 	[ -z "$AUTO_MERGE" ] && exit 0 # when -c flag set via sbox not sbox-mgt
 fi
 
@@ -1002,7 +1043,7 @@ if [ -z "$AUTO_MERGE" ]; then
 			[Yy]* ) 
 				sbox-fstool merge "$CONTAINER_NAME" "$verbose_cmd" \
 					--snapshot-dir "$SNAPSHOT_DIR" \
-					--rootfs-dir '\' && \
+					--rootfs-dir '$ROOTFS_DIR' && \
 				echo "snapshot merged"
 				break
 				;;
@@ -1017,7 +1058,7 @@ elif $AUTO_MERGE; then
 	echo "auto merge"
 	sbox-fstool merge "$CONTAINER_NAME" "$verbose_cmd" \
 		--snapshot-dir "$SNAPSHOT_DIR" \
-		--rootfs-dir '\' && \
+		--rootfs-dir '$ROOTFS_DIR' && \
 	echo "snapshot merged"
 else
 	echo "Abort."
