bug fix in fstool unable to copy directory to override deleted files

diff --git a/sbox-fstool b/sbox-fstool
--- a/sbox-fstool
+++ b/sbox-fstool
@@ -134,6 +134,25 @@ same_content() {
 }
 
 #############################################################
+# Takes error messages from 'cp' as input,
+# delete target non-directory, mark-deletion file so source 
+# directory will be able to copy over.
+#############################################################
+force_cp() {
+	cat | \
+	sed -nE "s/cp: cannot.+ '(.+)' .+ '(.+)'/\1 \2/p" | \
+	while IFS=" " read -r to from; do
+		if is_removed "$to"; then 
+			$VERBOSE && echo "force copy: $from ==> $to"
+			rm -r "$to"
+			cp -r "$from" "$to"
+		else
+			echo "copy error: $from ==> $to" >&2
+		fi
+	done
+}
+
+#############################################################
 # Copy all files/directories from dirty directory to snapshot 
 # directory.
 # If a directory is marked 'opaque' in dirty dir, then 
@@ -168,17 +187,17 @@ commit_all() {
 					--absolute-names --physical --recursive \
 					"$path_dirty")
 
-	# remove deleted files/directories
+	# remove deleted files/directories in dirty dir
 	find "$path_dirty" -type c -perm 0 | while IFS=$'\n' read -r deleted; do
 		path_relative=$(echo "$deleted" | cut -c$((path_wc+1))-)
 		snapshot=$(realpath -esq "$path_snapshot$path_relative")
-		$VERBOSE && echo "remove deleted: $snapshot"
+		$VERBOSE && echo "remove deleted file: $snapshot"
 		rm -r "$snapshot"
 	done
 
 	# move directory
 	$VERBOSE && echo "move dir: $path_dirty -> $path_snapshot"
-	cp -aTf "$path_dirty" "$path_snapshot"
+	cp -aTf "$path_dirty" "$path_snapshot" 2>&1 | force_cp
 	rm -r "$path_dirty"
 	# mkdir "$path_dirty"
 }
@@ -259,7 +278,7 @@ merge_all() {
 
 	# move directory
 	$VERBOSE && echo "move dir: $snapshot_dir -> $rootfs_dir"
-	cp -aTf "$snapshot_dir" "$rootfs_dir"
+	cp -aTf "$snapshot_dir" "$rootfs_dir" 2>&1 | force_cp
 	rm -r "$snapshot_dir"
 	# mkdir "$snapshot_dir"
 }
